-- Rollback de REF-BOOT-02-cleanup-drop-boot-diag.sql — recria o SCHEMA vazio de boot_diag (estrutura +
-- policy + grants capturados ao vivo antes da remocao). Os dados coletados durante a investigacao
-- (1778 linhas) NAO sao restaurados (nao foram exportados; eram so telemetria de boot, sem PII, e as
-- conclusoes ja estao documentadas na memoria do projeto REF-BOOT-02).
--
-- So faz sentido rodar se o dono decidir reativar a coleta de telemetria de boot no futuro — o coletor
-- v3 do index.html e os checkpoints no codigo TAMBEM precisariam voltar (nao ficam neste rollback,
-- que so cobre o schema do banco).
BEGIN;

CREATE TABLE IF NOT EXISTS public.boot_diag (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id     text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  device_id    text,
  run_id       integer,
  build        text,
  phase        text,
  ua           text,
  mounted      boolean,
  first_paint  boolean,
  mc_alive     boolean,
  last_step    text,
  hb_count     integer,
  payload      jsonb
);

ALTER TABLE public.boot_diag ENABLE ROW LEVEL SECURITY;

CREATE POLICY boot_diag_anon_insert ON public.boot_diag
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

GRANT INSERT ON public.boot_diag TO anon, authenticated;

COMMIT;

NOTIFY pgrst, 'reload schema';
